### ISSUE TITLE
Object.keys called on non-object

### ISSUE THREAD

**Issue by mike-aungsan** [timkuijsten/node-mongo-key-escaper#1]
I am having this error.

node v0.12.0
npm 2.5.1

var testObj =  { "a": "b"};
escaper.escape(testObj, true)

{"code":"InternalError","message":"Object.keys called on non-object"}

**Comment by timkuijsten** [comment]
I've tried to install node v0.12 with nvm but I had some issues with nvm.

Then I tried to reproduce with node v0.10.36 and iojs 2.0.0 but `npm test` runs successful under both runtimes. Can you copy and paste the output when running the tests with `npm test`?

**Comment by timkuijsten** [comment]
is this still an issue?

**Comment by mike-aungsan** [comment]
It is good. 👍  Many Thanks

$ node -v
v6.2.2
$ npm -v
3.9.5
